version: '3'
services: 
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181"
    kafka:
        image: eugenepy/kafka-docker:latest 
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        environment:
            # HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
            KAFKA_ADVERTISED_HOST_NAME: localhost
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9093,PLAINTEXT_HOST://localhost:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_LISTENERS: PLAINTEXT://:9093,PLAINTEXT_HOST://:9092
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    
    mongo: # arctic 
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=akira_data
            - MONGO_INITDB_ROOT_PASSWORD=akira_data
        ports:
            - "27017:27017"

    schema_registry:
        image: "confluentinc/cp-schema-registry:5.1.0"
        hostname: schema_registry
        container_name: schema_registry
        depends_on:
            - zookeeper
            - kafka
        ports:
            - "8081:8081"
        environment:
            SCHEMA_REGISTRY_HOST_NAME: schema_registry
            SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"
            SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_ORIGIN: '*'
            SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_METHODS: 'GET,POST,PUT,OPTIONS'

    #akira_data:
    #    image: eugenepy/basket:latest 
    #    environment:
    #        - MODEL_TOPIC=model_topic
    #        - INVESTINGDOT_COM_TOPIC=investingdotcom
    #        - MONGO_URI=mongodb://akira_data:akira_data@mongo:27017
    
    #akira_env: # in charge of testing, and order management. 
    #    image: eugenepy/akira-env:latest 
    #    environment:
    #        - MODEL_TOPIC=model_topic
    #        - ORDER_TOPIC=orders 
    #        - MONGO_URI=${MONGO_URI}
   
    #basket: # provide basket functionality. 
    #    image: eugenepy/basket:latest 
    #    build: .
    #    depends_on:
    #        - akira_env
    #        - akira_data

    #    environment:
    #        - DATA_TOPIC=${INVESTINGDOT_COM_TOPIC}
    #        - MODEL_TOPIC=${MODEL_TOPIC}
    #        - TASK_TOPIC=${TASK_QUQUE_TOPIC} 
    #        - ORDER_TOPIC=${ORDER_TOPIC}
    #        - MONGO_URI=${MONGO_URI}

