version: '3'
services: 
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181"
    kafka:
        image: eugenepy/kafka-docker:latest 
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        environment:
            # HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
            KAFKA_ADVERTISED_HOST_NAME: localhost
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9093,PLAINTEXT_HOST://localhost:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_LISTENERS: PLAINTEXT://:9093,PLAINTEXT_HOST://:9092
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

    mongo: # arctic 
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=akira_data
            - MONGO_INITDB_ROOT_PASSWORD=akira_data
        ports:
            - 27017:27017