version: '3'
services: 
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181"
    kafka:
        image: eugenepy/kafka-docker:latest 
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        environment:
            # HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
            KAFKA_ADVERTISED_HOST_NAME: localhost
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9093,PLAINTEXT_HOST://localhost:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_LISTENERS: PLAINTEXT://:9093,PLAINTEXT_HOST://:9092
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

    mongo: # arctic 
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=akira_data
            - MONGO_INITDB_ROOT_PASSWORD=akira_data
        ports:
            - 27017:27017

    quote-producer:
        image: eugenepy/data-pipeline:latest
        depends_on: 
            - mongo
            - kafka
        environment:
            - MONGODB_URI=mongodb://akira_data:akira_data@mongo:27017
            - KAFKA_BOOSTRAPHOST=kafka:9093
        command: "python akira/data_pipeline/server/run_websocket.py 1 2 --max_retry=-1" # streaming task
        restart: on-failure

    
    data-pipeline:
        image: eugenepy/data-pipeline:latest 
        depends_on:
            - quote-producer
        environment:
            - KAFKA_BOOSTRAPHOST=kafka:9093
            - MONGODB_URI=mongodb://akira_data:akira_data@mongo:27017
            - MODEL_TOPIC=model_topic
            - INVESTINGDOT_COM_TOPIC=investingdotcom
        command: "python akira/data_pipeline/server/app.py worker -l info"
        restart: on-failure

    #position-manger: # in charge of testing, and order management. 
    #    image: eugenepy/position-manager:latest
    #    environment:
    #        - KAFKA_BOOSTRAPHOST=kafka:9092
    #        - MODEL_TOPIC=model_topic
    #        - ORDER_TOPIC=orders 
    #        - MONGODB_URI=${MONGODB_URI}
    #    restart: on-failure

   
    #basket: # provide basket functionality. 
    #    image: eugenepy/basket:latest 
    #    build: .
    #    depends_on:
    #        - akira_env
    #        - akira_data

    #    environment:
    #        - DATA_TOPIC=${INVESTINGDOT_COM_TOPIC}
    #        - MODEL_TOPIC=${MODEL_TOPIC}
    #        - TASK_TOPIC=${TASK_QUQUE_TOPIC} 
    #        - ORDER_TOPIC=${ORDER_TOPIC}
    #        - MONGO_URI=${MONGO_URI}